---
- name: Ansible Playbook for localhost
  hosts: all

  tasks:
    - name: Ping test
      ansible.builtin.ping:
        data: "pong"

    - name: Clone xeokit-docs repository
      ansible.builtin.git:
        repo: https://github.com/xeokit/xeokit-docs.git
        dest: "{{ xeokit_docs_location }}"
        force: true

    - name: Prepare environment
      ansible.builtin.command: task docker:prepare-env TARGET=production
      args:
        chdir: "{{ xeokit_docs_location }}"

    - name: Replace GIT_HASH in docusaurus.config.ts before build
      ansible.builtin.command: task doc:set-version
      args:
        chdir: "{{ xeokit_docs_location }}"

    - name: Build images before trying to restart services
      ansible.builtin.command: task docker:compose-build
      args:
        chdir: "{{ xeokit_docs_location }}"

    - name: Tear down existing services
      community.docker.docker_compose_v2:
        project_src: "{{ xeokit_docs_location }}"
        state: absent
        remove_orphans: true
      become: true

    - name: Create and start services
      community.docker.docker_compose_v2:
        project_src: "{{ xeokit_docs_location }}"

