FROM node:22-alpine3.20 AS build

WORKDIR /app

RUN npm i pnpm@10.11.0 -g

COPY . .

RUN pnpm install
RUN pnpm run doc:sdk:generate
RUN pnpm run doc:build

FROM nginx:1.28-alpine AS runtime

COPY --from=build /app/build /usr/share/nginx/html
COPY ./.docker/docusaurus/nginx/default.conf /etc/nginx/conf.d/default.conf
