FROM node:22-alpine3.20 AS build

WORKDIR /app

COPY . .

RUN npm i pnpm@10.11.0 -g
RUN pnpm install

RUN pnpm run doc:build

# CMD ["pnpm", "run", "doc:serve"]

FROM nginx:1.28-alpine AS runtime

COPY --from=build /app/build /usr/share/nginx/html
