packages:
  - 'placeholder/*'

catalogs:
  docusaurus-base:
    "@docusaurus/core": "3.7.0"
    "@docusaurus/module-type-aliases": "3.7.0"
    "@docusaurus/preset-classic": "3.7.0"
    "@docusaurus/tsconfig": "3.7.0"
    "@docusaurus/types": "3.7.0"
    "@mdx-js/react": "^3.0.0"
    "@types/react": "^19.1.4"
    "clsx": "^2.0.0"
    "prism-react-renderer": "^2.3.0"
    "react": "^19.0.0"
    "react-dom": "^19.0.0"
    "typescript": "~5.6.2"
  docusaurus-extensions:
    "@docusaurus/theme-live-codeblock": "^3.7.0"
    "@docusaurus/theme-mermaid": "^3.7.0"
    "@easyops-cn/docusaurus-search-local": "^0.49.2"
    "docusaurus-plugin-openapi-docs": "^4.3.7"
    "docusaurus-theme-openapi-docs": "^4.3.7"
    "docusaurus-plugin-typedoc": "^1.3.0"
    "typedoc": "^0.28.2"
    "typedoc-plugin-markdown": "^4.6.2"
  lint:
    "@commitlint/cli": "^19.8.1"
    "@commitlint/config-conventional": "^19.8.1"
    "@eslint/js": "^9.25.1"
    "@stylistic/eslint-plugin": "^5.0.0"
    "eslint": "^9.25.1"
    "typescript-eslint": "^8.31.1"
  script:
    "@types/nunjucks": "^3.2.6"
    "arktype": "^2.1.20"
    "chalk": "^5.4.1"
    "dotenv-cli": "^8.0.0"
    "husky": "^9.1.7"
    "nunjucks": "^3.2.4"
    "tsx": "^4.19.3"
