networks:
  xd-net:
    external: true

services:
  docusaurus:
    container_name: xd-docusaurus
    image: xeokit/xd-docusaurus:latest
    build:
      context: .
      dockerfile: ./.docker/docusaurus/Dockerfile.prod
    restart: always
    networks:
      - xd-net
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=xd-net"

      - "traefik.http.routers.docusaurus.entrypoints=websecure"
      - "traefik.http.routers.docusaurus.rule=Host(`${XD_STACK_DOMAIN}`)"
      - "traefik.http.routers.docusaurus.tls=true"
      - "traefik.http.routers.docusaurus.tls.certresolver=letsencrypt"
      - "traefik.http.services.docusaurus.loadbalancer.server.port=80"

  # sdk-examples:
  #   container_name: xd-sdk-examples
  #   image: xeokit/xd-sdk-examples:latest
  #   build:
  #     context: ./_submodules/sdk
  #     dockerfile: ../../.docker/sdk-examples/Dockerfile.prod
  #   restart: always
  #   networks:
  #     - xd-net
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.docker.network=xd-net"

  #     - "traefik.http.routers.sdk-examples.entrypoints=websecure"
  #     - "traefik.http.routers.sdk-examples.rule=Host(`${XD_SDK_EXAMPLES_SUBDOMAIN}.${XD_STACK_DOMAIN}`)"
  #     - "traefik.http.routers.sdk-examples.tls=true"
  #     - "traefik.http.routers.sdk-examples.tls.certresolver=letsencrypt"
  #     - "traefik.http.services.sdk-examples.loadbalancer.server.port=80"
