FROM node:22-alpine3.20 AS build

WORKDIR /app

RUN npm i pnpm@10.11.0 -g

COPY . .

RUN pnpm install
RUN pnpm run examples:build

FROM nginx:1.28-alpine AS runtime

COPY --from=build /app/packages/examples/dist /usr/share/nginx/html
